"""Add ICP identity fields to User model

Revision ID: 654fb179dc9e
Revises: dff0b6573361
Create Date: 2026-03-19 20:38:46.210320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654fb179dc9e'
down_revision: Union[str, None] = 'dff0b6573361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dfx_identity_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('principal_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('encrypted_identity_key', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('wallet_cycles_balance', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('identity_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'identity_created_at')
    op.drop_column('users', 'wallet_cycles_balance')
    op.drop_column('users', 'encrypted_identity_key')
    op.drop_column('users', 'principal_id')
    op.drop_column('users', 'dfx_identity_name')
    # ### end Alembic commands ###
