"""Add deployment shared canister fields

Revision ID: dff0b6573361
Revises: 001_initial_schema
Create Date: 2026-03-18 14:12:51.211270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff0b6573361'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('canisters_principal_id_key', 'canisters', type_='unique')
    op.add_column('deployments', sa.Column('message', sa.Text(), nullable=True))
    op.add_column('deployments', sa.Column('error_details', sa.Text(), nullable=True))
    op.add_column('deployments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('deployments', sa.Column('canister_id', sa.String(length=255), nullable=True))
    op.add_column('deployments', sa.Column('project_path', sa.String(length=255), nullable=True))
    op.add_column('deployments', sa.Column('deployment_url', sa.String(length=500), nullable=True))
    op.drop_constraint('deployments_task_id_key', 'deployments', type_='unique')
    op.create_index(op.f('ix_deployments_canister_id'), 'deployments', ['canister_id'], unique=False)
    op.drop_constraint('projects_canister_id_key', 'projects', type_='unique')
    op.drop_constraint('projects_url_key', 'projects', type_='unique')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_unique_constraint('projects_url_key', 'projects', ['url'])
    op.create_unique_constraint('projects_canister_id_key', 'projects', ['canister_id'])
    op.drop_index(op.f('ix_deployments_canister_id'), table_name='deployments')
    op.create_unique_constraint('deployments_task_id_key', 'deployments', ['task_id'])
    op.drop_column('deployments', 'deployment_url')
    op.drop_column('deployments', 'project_path')
    op.drop_column('deployments', 'canister_id')
    op.drop_column('deployments', 'updated_at')
    op.drop_column('deployments', 'error_details')
    op.drop_column('deployments', 'message')
    op.create_unique_constraint('canisters_principal_id_key', 'canisters', ['principal_id'])
    # ### end Alembic commands ###
